package com.example.data.local.entity

import androidx.room.Entity
import androidx.room.PrimaryKey
import java.util.Locale
import java.util.UUID
import kotlin.math.sqrt

/**
 * Offline-first Farmer Entity matching the TraceHarvest Central Registry specification.
 * Conforms to the 6 Geopolitical Zones and EUDR WKT Boundary Standard.
 */
@Entity(tableName = "farmers")
data class FarmerEntity(
    @PrimaryKey
    val localId: String = UUID.randomUUID().toString(), // UUID generated on device
    val serverId: String? = null,                        // null until synced
    val farmerCode: String = "",                         // generated by backend or pending
    val name: String = "",
    val phone: String = "",
    val zone: String = "NW",                             // NW, NE, NC, SW, SE, SS
    val gpsLat: Double? = null,
    val gpsLng: Double? = null,
    val gpsAccuracy: Float? = null,
    val farmBoundaryWkt: String? = null,                 // POLYGON((lng lat, ...))
    val farmAreaHectares: Double? = null,
    val cropType: String = "",
    val cooperative: String? = null,
    val photoPath: String? = null,                       // local file path
    val photoConsent: Boolean = false,
    val gender: String = "MALE",                         // MALE or FEMALE for regional avatar
    val syncStatus: String = "pending_sync",             // PENDING, SYNCED, FAILED
    val createdAt: Long = System.currentTimeMillis(),

    // Domain extensions for Nigerian agricultural export provenance
    val id: Long = 0,
    val fullName: String = name,
    val phoneNumber: String = phone,
    val state: String = "Kano",
    val lga: String = "Dambatta",
    val community: String = "",
    val crop: String = cropType,
    val farmSize: Double = farmAreaHectares ?: 1.0,
    val farmSizeUnit: String = "hectares",
    val farmSizeHectares: Double = farmAreaHectares ?: when (farmSizeUnit.lowercase(Locale.ROOT)) {
        "acres" -> farmSize * 0.4047
        "plots" -> farmSize * 0.05
        else -> farmSize
    },
    val latitude: Double = gpsLat ?: 0.0,
    val longitude: Double = gpsLng ?: 0.0,
    val registrationTimestamp: Long = createdAt,
    val isSynced: Boolean = syncStatus == "SYNCED" || syncStatus == "synced",
    val farmerDisplayId: String = if (farmerCode.isNotBlank()) farmerCode else "PENDING",
    val gpsPolygon: String = "",
    val agentId: String = "AGENT-NG-042",
    val clientUuid: String = localId
) {
    /**
     * Active Local Database Identifier
     */
    val farmerLocalId: Long get() = id

    /**
     * Human-readable formatted center GPS coordinates
     */
    val effectiveLatitude: Double get() = if (latitude != 0.0) latitude else (gpsLat ?: 0.0)
    val effectiveLongitude: Double get() = if (longitude != 0.0) longitude else (gpsLng ?: 0.0)
    val gpsCoordinates: String get() = "${"%.4f".format(effectiveLatitude)}°N, ${"%.4f".format(effectiveLongitude)}°E"

    /**
     * Returns the 4 corner boundary polygon coordinates (geotagged perimeter)
     */
    fun getPolygonCoordinates(): List<Pair<Double, Double>> {
        if (!farmBoundaryWkt.isNullOrBlank()) {
            try {
                // Parse POLYGON((lng lat, lng lat, ...))
                val content = farmBoundaryWkt.substringAfter("((").substringBefore("))")
                val pairs = content.split(",").mapNotNull { p ->
                    val parts = p.trim().split(" ")
                    if (parts.size >= 2) {
                        Pair(parts[1].toDouble(), parts[0].toDouble()) // (lat, lng)
                    } else null
                }
                if (pairs.isNotEmpty()) return pairs
            } catch (_: Exception) {}
        }

        if (gpsPolygon.isNotBlank()) {
            try {
                val parsed = gpsPolygon.split(";").mapNotNull { entry ->
                    val parts = entry.split(",")
                    if (parts.size >= 2) {
                        Pair(parts[0].trim().toDouble(), parts[1].trim().toDouble())
                    } else null
                }
                if (parsed.isNotEmpty()) return parsed
            } catch (_: Exception) {}
        }

        val delta = (sqrt(farmSizeHectares.coerceAtLeast(0.5)) * 0.00075)
        return listOf(
            Pair(effectiveLatitude + delta, effectiveLongitude - delta), // NW
            Pair(effectiveLatitude + delta, effectiveLongitude + delta), // NE
            Pair(effectiveLatitude - delta, effectiveLongitude + delta), // SE
            Pair(effectiveLatitude - delta, effectiveLongitude - delta)  // SW
        )
    }
}
